import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import 'package:remember_this_text/features/contacts/application/sidebar_cassette_spec/resolver_tools/filtered_picker_sections_provider.dart';
import 'package:remember_this_text/features/contacts/application/sidebar_cassette_spec/resolver_tools/picker_filter_mode_provider.dart';
import 'package:remember_this_text/features/contacts/application/sidebar_cassette_spec/resolver_tools/unified_picker_sections_provider.dart';
import 'package:remember_this_text/features/contacts/domain/participant_origin.dart';
import 'package:remember_this_text/features/contacts/infrastructure/repositories/contacts_list_repository.dart';
import 'package:remember_this_text/features/contacts/presentation/widgets/grouped_contact_selector.dart';

void main() {
  group('FullContactPicker', () {
    testWidgets('updates visible rows when switching All and Favourites', (
      tester,
    ) async {
      final container = ProviderContainer(
        overrides: [
          pickerFilterProvider.overrideWith(_TestPickerFilter.new),
          filteredPickerSectionsProvider.overrideWith((ref) async {
            final mode = ref.watch(pickerFilterProvider);
            return switch (mode) {
              PickerFilterMode.all => _allSections,
              PickerFilterMode.favouritesOnly => _favouritesOnlySections,
            };
          }),
        ],
      );

      await tester.pumpWidget(
        UncontrolledProviderScope(
          container: container,
          child: Directionality(
            textDirection: TextDirection.ltr,
            child: PageStorage(
              bucket: PageStorageBucket(),
              child: const SizedBox(
                width: 320,
                height: 420,
                child: FullContactPicker(
                  selectedParticipantId: null,
                  onContactSelected: _noopContactSelection,
                ),
              ),
            ),
          ),
        ),
      );

      await tester.pumpAndSettle();

      expect(find.text('Alice Abel'), findsOneWidget);
      expect(find.text('Bruno Baker'), findsOneWidget);
      expect(find.text('Alice'), findsNothing);
      expect(find.text('Bruno'), findsNothing);

      await tester.tap(find.text('Favourites'));
      await tester.pumpAndSettle();

      expect(find.text('Alice Abel'), findsNothing);
      expect(find.text('Bruno Baker'), findsOneWidget);

      container.dispose();
    });

    testWidgets(
      're-entering chooser state does not keep stale rows or toggle meaning',
      (tester) async {
        await _pumpPickerShell(
          tester,
          child: const FullContactPicker(
            selectedParticipantId: null,
            onContactSelected: _noopContactSelection,
            currentMode: PickerFilterMode.all,
            unifiedSections: _allSections,
          ),
        );

        await tester.pumpAndSettle();

        expect(find.text('Alice Abel'), findsOneWidget);
        expect(find.text('Bruno Baker'), findsOneWidget);

        await _pumpPickerShell(
          tester,
          child: const SizedBox(width: 320, height: 420, child: Text('hero')),
        );

        await tester.pumpAndSettle();

        expect(find.text('hero'), findsOneWidget);
        expect(find.text('Alice Abel'), findsNothing);
        expect(find.text('Bruno Baker'), findsNothing);

        await _pumpPickerShell(
          tester,
          child: const FullContactPicker(
            selectedParticipantId: null,
            onContactSelected: _noopContactSelection,
            currentMode: PickerFilterMode.favouritesOnly,
            unifiedSections: _favouritesOnlySections,
          ),
        );

        await tester.pumpAndSettle();

        expect(find.text('hero'), findsNothing);
        expect(find.text('Alice Abel'), findsNothing);
        expect(find.text('Bruno Baker'), findsOneWidget);
        expect(find.text('Favourites'), findsOneWidget);
      },
    );
  });
}

Future<void> _pumpPickerShell(WidgetTester tester, {required Widget child}) {
  return tester.pumpWidget(
    ProviderScope(
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: PageStorage(
          bucket: PageStorageBucket(),
          child: SizedBox(width: 320, height: 420, child: child),
        ),
      ),
    ),
  );
}

void _noopContactSelection(int _) {}

class _TestPickerFilter extends PickerFilter {
  @override
  PickerFilterMode build() {
    return PickerFilterMode.all;
  }

  @override
  Future<void> setMode(PickerFilterMode mode) async {
    state = mode;
  }
}

const ContactSummary _aliceContact = ContactSummary(
  participantId: 1,
  displayName: 'Alice Abel',
  autoGeneratedName: 'Alice Abel',
  totalChats: 1,
  totalMessages: 3,
  origin: ParticipantOrigin.working,
  handleCount: 1,
);

const ContactSummary _brunoContact = ContactSummary(
  participantId: 2,
  displayName: 'Bruno Baker',
  autoGeneratedName: 'Bruno Baker',
  totalChats: 1,
  totalMessages: 5,
  origin: ParticipantOrigin.working,
  handleCount: 1,
);

const UnifiedPickerSections _allSections = UnifiedPickerSections(
  sections: [
    PickerSection(
      key: 'A',
      label: 'A',
      contacts: [_aliceContact, _brunoContact],
      type: PickerSectionType.alphabetical,
    ),
  ],
  alphabeticalLetters: ['A'],
  alphabeticalStartIndex: 0,
  allFavoriteIds: {2},
);

const UnifiedPickerSections _favouritesOnlySections = UnifiedPickerSections(
  sections: [
    PickerSection(
      key: 'B',
      label: 'B',
      contacts: [_brunoContact],
      type: PickerSectionType.alphabetical,
    ),
  ],
  alphabeticalLetters: ['B'],
  alphabeticalStartIndex: 0,
  allFavoriteIds: {2},
);
