import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import '../../../../config/theme/colors/theme_colors.dart';
import '../../../../config/theme/theme_typography.dart';
import 'contact_initial_badge.dart';

class ContactHighlightRow extends StatefulWidget {
  const ContactHighlightRow({
    super.key,
    required this.displayName,
    this.summaryLine,
    this.useHeroTitleStyle = false,
    this.showFavoriteIndicator = false,
    this.contentPadding,
    this.contentLeftGutter,
    this.onHoverStart,
    this.onTap,
  });

  final String displayName;
  final String? summaryLine;
  final bool useHeroTitleStyle;
  final bool showFavoriteIndicator;
  final EdgeInsets? contentPadding;
  final double? contentLeftGutter;
  final VoidCallback? onHoverStart;
  final VoidCallback? onTap;

  @override
  State<ContactHighlightRow> createState() => _ContactHighlightRowState();
}

class _ContactHighlightRowState extends State<ContactHighlightRow> {
  bool _isHovered = false;

  @override
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, ref, child) {
        ref.watch(themeColorsProvider);
        final colors = ref.read(themeColorsProvider.notifier);
        final typography = ref.watch(themeTypographyProvider);

        final titleStyle = widget.useHeroTitleStyle
            ? typography.heroTitle
            : typography.body;

        final content = Padding(
          padding:
              widget.contentPadding ??
              const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          child: Row(
            children: [
              if (widget.contentLeftGutter != null)
                SizedBox(width: widget.contentLeftGutter),
              if (!widget.useHeroTitleStyle) ...[
                ContactInitialBadge(displayName: widget.displayName),
                if (widget.showFavoriteIndicator) ...[
                  const SizedBox(width: 4),
                  Icon(
                    CupertinoIcons.star_fill,
                    size: 10,
                    color: colors.interactiveHints.favoriteStar,
                  ),
                  const SizedBox(width: 4),
                ] else
                  const SizedBox(width: 8),
              ],
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      widget.displayName,
                      style: titleStyle,
                      overflow: TextOverflow.ellipsis,
                    ),
                    if (widget.summaryLine != null) ...[
                      const SizedBox(height: 6),
                      Text(
                        widget.summaryLine!,
                        style: typography.caption,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ],
                ),
              ),
            ],
          ),
        );

        final decorated = DecoratedBox(
          decoration: BoxDecoration(
            color: _isHovered
                ? colors.accents.primary.withValues(alpha: 0.15)
                : Colors.transparent,
            borderRadius: BorderRadius.circular(10),
          ),
          child: content,
        );

        final onTapCallback = widget.onTap;
        if (onTapCallback == null) {
          return MouseRegion(
            onEnter: (_) {
              widget.onHoverStart?.call();
              setState(() => _isHovered = true);
            },
            onExit: (_) => setState(() => _isHovered = false),
            child: decorated,
          );
        }

        return MouseRegion(
          cursor: SystemMouseCursors.click,
          onEnter: (_) {
            widget.onHoverStart?.call();
            setState(() => _isHovered = true);
          },
          onExit: (_) => setState(() => _isHovered = false),
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: onTapCallback,
            child: decorated,
          ),
        );
      },
    );
  }
}

class ContactHeroHeaderHighlight extends ConsumerWidget {
  const ContactHeroHeaderHighlight({
    super.key,
    required this.displayName,
    required this.autoGeneratedName,
    required this.summaryLine,
    this.onEdit,
    this.isFavorite = false,
    this.onToggleFavorite,
  });

  /// The effective display name (user override if set, else auto-generated).
  final String displayName;

  /// The algorithm-generated name from AddressBook import.
  /// Shown as identity anchor subtitle when different from displayName.
  final String autoGeneratedName;

  final String summaryLine;

  /// Callback for "edit" link to customize the display name.
  /// If null, the name is not editable.
  final VoidCallback? onEdit;

  /// Whether this contact is currently a favorite.
  final bool isFavorite;

  /// Called when the user wants to toggle favorite status.
  /// The callback receives the *desired* new state (`true` = add, `false` = remove).
  /// If null, the star toggle is hidden.
  final ValueChanged<bool>? onToggleFavorite;

  /// Whether the display name is user-customized (different from auto-generated).
  bool get _isUserOverridden => displayName != autoGeneratedName;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch the brightness state to trigger rebuilds
    ref.watch(themeColorsProvider);
    final colors = ref.read(themeColorsProvider.notifier);
    final typography = ref.watch(themeTypographyProvider);

    final tint = colors.accents.primary.withValues(alpha: 0.10);
    final accent = colors.accents.primary.withValues(alpha: 0.75);

    return ConstrainedBox(
      constraints: const BoxConstraints(minHeight: 64),
      child: DecoratedBox(
        decoration: BoxDecoration(
          color: tint,
          borderRadius: BorderRadius.circular(10),
        ),
        child: Row(
          children: [
            DecoratedBox(
              decoration: BoxDecoration(
                color: accent,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.circular(10),
                  bottomLeft: Radius.circular(10),
                ),
              ),
              child: const SizedBox(width: 4),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 10,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    // Primary: Name + action icons as a single row
                    Row(
                      children: [
                        // Name + pencil as single interactive target
                        Flexible(
                          child: onEdit != null
                              ? _NameEditTarget(
                                  displayName: displayName,
                                  isUserOverridden: _isUserOverridden,
                                  onEdit: onEdit!,
                                  typography: typography,
                                  colors: colors,
                                )
                              : Text(
                                  displayName,
                                  style: typography.heroTitle,
                                  overflow: TextOverflow.ellipsis,
                                ),
                        ),
                        // Favorite star toggle (parallel to pencil)
                        if (onToggleFavorite != null)
                          Padding(
                            padding: const EdgeInsets.only(left: 4),
                            child: _FavoriteStarToggle(
                              isFavorite: isFavorite,
                              onToggle: onToggleFavorite!,
                              colors: colors,
                            ),
                          ),
                      ],
                    ),

                    // Vertical separation from title
                    const SizedBox(height: 10),

                    // Secondary: Identity anchor (only shown when overridden)
                    if (_isUserOverridden) ...[
                      Text(
                        autoGeneratedName,
                        style: typography.heroSubtitle,
                        overflow: TextOverflow.ellipsis,
                      ),
                      const SizedBox(height: 4),
                    ],

                    // Metadata: summary line
                    Text(
                      summaryLine,
                      style: typography.heroMeta,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// Interactive target combining name text and pencil icon.
///
/// Per the interaction spec:
/// - The NAME is the control, pencil is secondary hint
/// - Single hover target for name + icon
/// - Hover: name changes to accent, pencil increases contrast
/// - Focus: mirrors hover state
/// - Click/Enter/Space opens edit dialog
/// - Tooltip after 700ms (assistive only)
class _NameEditTarget extends StatefulWidget {
  const _NameEditTarget({
    required this.displayName,
    required this.isUserOverridden,
    required this.onEdit,
    required this.typography,
    required this.colors,
  });

  final String displayName;
  final bool isUserOverridden;
  final VoidCallback onEdit;
  final ThemeTypography typography;
  final ThemeColors colors;

  @override
  State<_NameEditTarget> createState() => _NameEditTargetState();
}

class _NameEditTargetState extends State<_NameEditTarget> {
  bool _isHovered = false;
  bool _isFocused = false;

  bool get _isActive => _isHovered || _isFocused;

  @override
  Widget build(BuildContext context) {
    final hints = widget.colors.interactiveHints;

    // Pencil icon contrast: very subtle at rest, more visible on hover
    // If user-overridden, slightly more visible at rest to hint customization
    final pencilRestAlpha = widget.isUserOverridden
        ? hints.iconRestAlphaOverridden
        : hints.iconRestAlpha;
    final pencilColor = widget.colors.content.textPrimary.withValues(
      alpha: _isActive ? hints.iconActiveAlpha : pencilRestAlpha,
    );

    // Name color: stays primary always (no color change on hover)
    final nameColor = widget.colors.content.textPrimary;

    // Subtle background lift on hover
    final bgColor = _isActive ? hints.backgroundLift : Colors.transparent;

    return Semantics(
      button: true,
      label: 'Edit display name: ${widget.displayName}',
      child: Focus(
        onFocusChange: (focused) => setState(() => _isFocused = focused),
        onKeyEvent: (node, event) {
          // Enter or Space activates
          if (event is KeyDownEvent &&
              (event.logicalKey == LogicalKeyboardKey.enter ||
                  event.logicalKey == LogicalKeyboardKey.space)) {
            widget.onEdit();
            return KeyEventResult.handled;
          }
          return KeyEventResult.ignored;
        },
        child: Tooltip(
          message: 'Click to edit display name',
          waitDuration: const Duration(milliseconds: 700),
          preferBelow: false,
          child: MouseRegion(
            cursor: SystemMouseCursors.click,
            onEnter: (_) => setState(() => _isHovered = true),
            onExit: (_) => setState(() => _isHovered = false),
            child: GestureDetector(
              behavior: HitTestBehavior.opaque,
              onTap: widget.onEdit,
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 120),
                decoration: BoxDecoration(
                  color: bgColor,
                  borderRadius: BorderRadius.circular(hints.cornerRadius),
                ),
                // Asymmetric padding: more vertical for breathing room
                padding: EdgeInsets.symmetric(
                  horizontal: hints.paddingHorizontal,
                  vertical: hints.paddingVertical,
                ),
                // Negative margin to offset horizontal padding
                transform: Matrix4.translationValues(
                  -hints.paddingHorizontal,
                  0,
                  0,
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Flexible(
                      child: Text(
                        widget.displayName,
                        style: widget.typography.heroTitle.copyWith(
                          color: nameColor,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                    const SizedBox(width: 6),
                    Icon(CupertinoIcons.pencil, size: 16, color: pencilColor),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

/// Hover-revealed star icon for toggling favorite status.
///
/// Behavior:
/// - **Not favorited, resting**: star hidden (0 opacity).
/// - **Not favorited, hovered (parent)**: outlined star fades in at low contrast.
/// - **Favorited, resting**: filled star visible but muted.
/// - **Favorited, hovered**: filled star at full contrast.
///
/// Favoriting is immediate on click.
/// Unfavoriting shows a confirmation popover (prevents accidents).
class _FavoriteStarToggle extends StatefulWidget {
  const _FavoriteStarToggle({
    required this.isFavorite,
    required this.onToggle,
    required this.colors,
  });

  final bool isFavorite;
  final ValueChanged<bool> onToggle;
  final ThemeColors colors;

  @override
  State<_FavoriteStarToggle> createState() => _FavoriteStarToggleState();
}

class _FavoriteStarToggleState extends State<_FavoriteStarToggle> {
  bool _isHovered = false;

  void _handleTap() {
    if (widget.isFavorite) {
      // Unfavorite: show confirmation popover
      _showUnfavoriteConfirmation();
    } else {
      // Favorite: immediate
      widget.onToggle(true);
    }
  }

  void _showUnfavoriteConfirmation() {
    final renderBox = context.findRenderObject()! as RenderBox;
    final overlay =
        Overlay.of(context).context.findRenderObject()! as RenderBox;
    final position = RelativeRect.fromRect(
      Rect.fromPoints(
        renderBox.localToGlobal(Offset.zero, ancestor: overlay),
        renderBox.localToGlobal(
          renderBox.size.bottomRight(Offset.zero),
          ancestor: overlay,
        ),
      ),
      Offset.zero & overlay.size,
    );

    showMenu<bool>(
      context: context,
      position: position,
      constraints: const BoxConstraints(maxWidth: 220),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
      items: [
        const PopupMenuItem<bool>(
          value: true,
          height: 36,
          child: Text('Remove from Favorites'),
        ),
      ],
    ).then((confirmed) {
      if (confirmed == true) {
        widget.onToggle(false);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final hints = widget.colors.interactiveHints;

    // Determine icon and color based on state
    final IconData icon;
    final Color color;

    if (widget.isFavorite) {
      icon = CupertinoIcons.star_fill;
      color = _isHovered
          ? hints.starFavoritedHover
          : hints.starFavoritedResting;
    } else {
      icon = CupertinoIcons.star;
      color = widget.colors.content.textPrimary.withValues(
        alpha: _isHovered ? hints.iconActiveAlpha : hints.iconRestAlpha,
      );
    }

    final tooltipMessage = widget.isFavorite
        ? 'Remove from Favorites'
        : 'Add to Favorites';

    return Semantics(
      button: true,
      label: tooltipMessage,
      child: Tooltip(
        message: tooltipMessage,
        waitDuration: const Duration(milliseconds: 700),
        preferBelow: false,
        child: MouseRegion(
          cursor: SystemMouseCursors.click,
          onEnter: (_) => setState(() => _isHovered = true),
          onExit: (_) => setState(() => _isHovered = false),
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: _handleTap,
            child: Padding(
              padding: const EdgeInsets.all(4),
              child: AnimatedSwitcher(
                duration: const Duration(milliseconds: 180),
                child: Icon(
                  icon,
                  key: ValueKey(widget.isFavorite),
                  size: 15,
                  color: color,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
