name: remember_this_text
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1

  # Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Functional programming
  dartz: ^0.10.1

  # Database
  drift: ^2.28.0

  # Utilities
  intl: ^0.20.2
  http: ^1.4.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  logger: ^2.6.1
  collection: ^1.19.1
  macos_ui: ^2.2.0
  macos_window_utils: ^1.5.0
  watcher: ^1.1.0
  url_launcher: ^6.3.0
  plist_parser: ^0.2.5

  # Date/Time manipulation
  jiffy: ^6.3.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.3
  sqlite3: ^2.4.6

  # Video playback
  video_player: ^2.8.1
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_macos_video: ^1.1.4
  uuid: ^4.5.1

  # Routing
  go_router: ^14.6.1

  flutter_rust_bridge: 2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  freezed: ^3.1.0
  json_serializable: ^6.8.0
  custom_lint: ^0.7.6
  analyzer: ^7.6.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.0
  drift_dev: ^2.28.0
  ddd_lints:
    path: custom_lint_plugins/ddd_lints

flutter:
  uses-material-design: true

dependency_overrides:
  macos_ui:
    path: packages/macos_ui_patched
