import '../../../../essentials/conversation_graph/domain/identity_key_bridge.dart';
import '../../../../essentials/db/infrastructure/data_sources/local/conversation_graph/conversation_graph_database.dart';
import '../../../../essentials/db/infrastructure/data_sources/local/overlay/overlay_database.dart';
import '../../application/read_models/contact_summary.dart';
import '../../application/read_models/contacts_list_reader.dart';
import '../../domain/overlay_virtual_contact.dart';
import '../../domain/participant_origin.dart';
import 'overlay_virtual_participants_reader.dart';
import 'participant_merge_utils.dart';

class GraphContactsListReader implements ContactsListReader {
  const GraphContactsListReader({
    required ConversationGraphDatabase graphDb,
    required OverlayDatabase overlayDb,
  }) : _graphDb = graphDb,
       _overlayDb = overlayDb;

  final ConversationGraphDatabase _graphDb;
  final OverlayDatabase _overlayDb;

  @override
  Future<List<ContactSummary>> readContacts() async {
    final virtualContacts = await OverlayVirtualParticipantsReader(
      overlayDb: _overlayDb,
    ).readVirtualParticipants();

    final graphSummaries = await _readGraphContactSummaries();
    final overlayHandlesByVP = await overlayHandleIdsByVirtualParticipant(
      _overlayDb,
    );
    final overlayVPHandleCounts = await overlayHandleCountsByVirtualParticipant(
      _overlayDb,
    );

    final virtualSummaries = await _readVirtualContactSummaries(
      virtualContacts: virtualContacts,
      overlayHandlesByVP: overlayHandlesByVP,
      overlayVPHandleCounts: overlayVPHandleCounts,
    );

    return [...graphSummaries, ...virtualSummaries];
  }

  Future<List<ContactSummary>> _readGraphContactSummaries() async {
    final participantOverrides = await participantOverridesById(_overlayDb);

    final rows = await _graphDb.selectRows('''
      SELECT
        c.contact_id AS contact_id,
        c.display_name AS display_name,
        c.given_name AS given_name,
        c.family_name AS family_name,
        c.organization AS organization,
        COUNT(DISTINCT contact_handle.handle_ss_id) AS handle_count,
        COUNT(DISTINCT chat_handle.chat_ss_id) AS total_chats,
        COUNT(DISTINCT ctm.message_ss_id) AS total_messages,
        MAX(m.date_utc) AS last_message_utc
      FROM contacts c
      JOIN contact_to_handle contact_handle
        ON contact_handle.contact_id = c.contact_id
      JOIN chat_to_handle chat_handle
        ON chat_handle.handle_ss_id = contact_handle.handle_ss_id
        OR EXISTS (
          SELECT 1
          FROM handle_aliases contact_alias
          WHERE contact_alias.handle_ss_id = chat_handle.handle_ss_id
            AND contact_alias.canonical_handle_ss_id =
              contact_handle.handle_ss_id
        )
      JOIN chat_to_message ctm
        ON ctm.chat_ss_id = chat_handle.chat_ss_id
      JOIN messages m ON m.ss_id = ctm.message_ss_id
      WHERE c.display_name IS NOT NULL
        AND c.display_name != ''
        AND c.display_name != 'Unknown Contact'
      GROUP BY c.contact_id
      HAVING COUNT(DISTINCT chat_handle.chat_ss_id) > 0
      ORDER BY c.display_name ASC
      ''');

    final summaries = <ContactSummary>[];
    for (final row in rows) {
      final contactId = _readNullableInt(row['contact_id']);
      final autoGeneratedName = (row['display_name'] as String?)?.trim();
      if (contactId == null ||
          autoGeneratedName == null ||
          autoGeneratedName.isEmpty ||
          isPlaceholderDisplayName(autoGeneratedName)) {
        continue;
      }

      final override = overlayValueForContactId(
        participantOverrides,
        contactId,
      );
      final overrideLabel = override?.displayNameOverride?.trim();
      final displayName = overrideLabel != null && overrideLabel.isNotEmpty
          ? overrideLabel
          : autoGeneratedName;

      summaries.add(
        ContactSummary(
          participantId: contactId,
          displayName: displayName,
          autoGeneratedName: autoGeneratedName,
          totalChats: _readInt(row['total_chats']),
          totalMessages: _readInt(row['total_messages']),
          lastMessageDate: _parseDate(row['last_message_utc'] as String?),
          origin: overrideLabel != null && overrideLabel.isNotEmpty
              ? ParticipantOrigin.overlayOverride
              : ParticipantOrigin.working,
          handleCount: _readInt(row['handle_count']),
          givenName: row['given_name'] as String?,
          familyName: row['family_name'] as String?,
          organization: row['organization'] as String?,
        ),
      );
    }

    summaries.sort((a, b) => a.displayName.compareTo(b.displayName));
    return summaries;
  }

  Future<List<ContactSummary>> _readVirtualContactSummaries({
    required List<OverlayVirtualContact> virtualContacts,
    required Map<int, Set<int>> overlayHandlesByVP,
    required Map<int, int> overlayVPHandleCounts,
  }) async {
    final virtualSummaries = <ContactSummary>[];
    for (final contact in virtualContacts) {
      if (isPlaceholderDisplayName(contact.displayName)) {
        continue;
      }
      final handleIds = overlayHandlesByVP[contact.id] ?? const <int>{};

      final metrics = await _calculateGraphMetricsForHandles(handleIds);
      if (metrics.totalChats == 0) {
        continue;
      }

      virtualSummaries.add(
        ContactSummary(
          participantId: contact.id,
          displayName: contact.displayName,
          autoGeneratedName: contact.displayName,
          totalChats: metrics.totalChats,
          totalMessages: metrics.totalMessages,
          lastMessageDate: metrics.lastMessageDate,
          origin: ParticipantOrigin.overlayVirtual,
          handleCount: overlayVPHandleCounts[contact.id] ?? handleIds.length,
          givenName: null,
          familyName: null,
          organization: null,
        ),
      );
    }

    virtualSummaries.sort((a, b) => a.displayName.compareTo(b.displayName));
    return virtualSummaries;
  }

  Future<_ParticipantMetrics> _calculateGraphMetricsForHandles(
    Set<int> handleIds,
  ) async {
    if (handleIds.isEmpty) {
      return const _ParticipantMetrics(
        totalChats: 0,
        totalMessages: 0,
        lastMessageDate: null,
      );
    }

    final graphHandleIds = <int>{};
    for (final handleId in handleIds) {
      graphHandleIds.addAll(handleOverlayKeyVariants(handleId));
    }

    final placeholders = List.filled(graphHandleIds.length, '?').join(', ');
    final rows = await _graphDb.selectRows(
      '''
      SELECT
        COUNT(DISTINCT cth.chat_ss_id) AS total_chats,
        COUNT(DISTINCT ctm.message_ss_id) AS total_messages,
        MAX(m.date_utc) AS last_message_utc
      FROM chat_to_handle cth
      JOIN chat_to_message ctm ON ctm.chat_ss_id = cth.chat_ss_id
      JOIN messages m ON m.ss_id = ctm.message_ss_id
      WHERE cth.handle_ss_id IN ($placeholders)
        OR cth.handle_ss_id IN (
          SELECT canonical_handle_ss_id
          FROM handle_aliases
          WHERE handle_ss_id IN ($placeholders)
        )
        OR EXISTS (
          SELECT 1
          FROM handle_aliases chat_alias
          WHERE chat_alias.handle_ss_id = cth.handle_ss_id
            AND chat_alias.canonical_handle_ss_id IN ($placeholders)
        )
      ''',
      <Object?>[...graphHandleIds, ...graphHandleIds, ...graphHandleIds],
    );
    if (rows.isEmpty) {
      return const _ParticipantMetrics(
        totalChats: 0,
        totalMessages: 0,
        lastMessageDate: null,
      );
    }

    final row = rows.single;
    final lastMessageUtc = row['last_message_utc'] as String?;
    final lastMessageDate = switch (lastMessageUtc) {
      null => null,
      '' => null,
      final String value => DateTime.tryParse(value)?.toLocal(),
    };

    return _ParticipantMetrics(
      totalChats: _readInt(row['total_chats']),
      totalMessages: _readInt(row['total_messages']),
      lastMessageDate: lastMessageDate,
    );
  }
}

class _ParticipantMetrics {
  const _ParticipantMetrics({
    required this.totalChats,
    required this.totalMessages,
    required this.lastMessageDate,
  });

  final int totalChats;
  final int totalMessages;
  final DateTime? lastMessageDate;
}

int _readInt(Object? value) {
  if (value is int) {
    return value;
  }
  if (value is BigInt) {
    return value.toInt();
  }
  if (value is num) {
    return value.toInt();
  }
  return int.parse(value.toString());
}

int? _readNullableInt(Object? value) {
  if (value is int) {
    return value;
  }
  if (value is BigInt) {
    return value.toInt();
  }
  if (value is num) {
    return value.toInt();
  }
  return null;
}

DateTime? _parseDate(String? value) {
  if (value == null || value.isEmpty) {
    return null;
  }
  return DateTime.tryParse(value)?.toLocal();
}
