import '../../../../essentials/conversation_graph/application/identity/retained_overlay_identity_bridge.dart';
import '../../../../essentials/db/infrastructure/data_sources/local/overlay/overlay_database.dart';
import '../../application/read_models/contact_summary.dart';
import '../../application/read_models/recent_contact_summary.dart';
import '../../application/read_models/recent_contacts_reader.dart';
import '../../domain/participant_origin.dart';

class OverlayRecentContactsReader implements RecentContactsReader {
  const OverlayRecentContactsReader({required OverlayDatabase overlayDb})
    : _overlayDb = overlayDb;

  final OverlayDatabase _overlayDb;

  @override
  Future<List<RecentContactSummary>> readRecentContacts({
    required List<ContactSummary> contacts,
  }) async {
    final recentRows = await _overlayDb.getRecentContacts(limit: 3);
    if (recentRows.isEmpty) {
      return const <RecentContactSummary>[];
    }

    final results = <RecentContactSummary>[];
    for (final recent in recentRows) {
      final contact = _findContactForRecent(contacts, recent.participantId);
      results.add(
        RecentContactSummary(
          participantId: contact.participantId,
          displayName: contact.displayName,
          lastAccessedUtc: recent.lastInteractionUtc != null
              ? DateTime.parse(recent.lastInteractionUtc!)
              : DateTime.parse(recent.createdAtUtc),
        ),
      );
    }

    return results;
  }
}

ContactSummary _findContactForRecent(
  List<ContactSummary> contacts,
  int recentParticipantId,
) {
  for (final contact in contacts) {
    if (contactIdsRepresentSamePerson(
      contact.participantId,
      recentParticipantId,
    )) {
      return contact;
    }
  }

  final fallbackName = 'Contact $recentParticipantId';
  return ContactSummary(
    participantId: recentParticipantId,
    displayName: fallbackName,
    autoGeneratedName: fallbackName,
    totalChats: 0,
    totalMessages: 0,
    origin: ParticipantOrigin.working,
    handleCount: 0,
    givenName: null,
    familyName: null,
    organization: null,
  );
}
