import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../../../essentials/db/feature_level_providers.dart';
import '../../domain/participant_origin.dart';
import 'contacts_list_repository.dart';

part 'recent_contacts_repository.g.dart';

/// Recent contact with participant info for display
class RecentContactSummary {
  const RecentContactSummary({
    required this.participantId,
    required this.displayName,
    required this.lastAccessedUtc,
  });

  final int participantId;
  final String displayName;
  final DateTime lastAccessedUtc;
}

/// Provides list of recently accessed contacts (up to 3).
/// Combines overlay DB recent access tracking with graph-backed contact
/// summaries.
/// The list persists across sessions via overlay.db.
///
/// ## Behavior
/// - Empty list in virgin state (no contacts picked yet)
/// - Shows up to 3 most recently accessed contacts
/// - Order: most recent first
/// - Persists across app restarts (stored in overlay.db)
@riverpod
Future<List<RecentContactSummary>> recentContacts(Ref ref) async {
  final overlayDb = await ref.watch(overlayDatabaseProvider.future);

  // Get recently accessed participant IDs from overlay DB (max 3)
  final recentFavorites = await overlayDb.getRecentContacts(limit: 3);

  // If no recent contacts tracked, return empty immediately
  if (recentFavorites.isEmpty) {
    return [];
  }

  // Wait for contacts to load (this properly awaits the async data)
  final allContacts = await ref.watch(contactsListRepositoryProvider.future);

  // Map recent participant IDs to contact summaries
  final results = <RecentContactSummary>[];
  for (final recent in recentFavorites) {
    final contact = allContacts.firstWhere(
      (c) => c.participantId == recent.participantId,
      orElse: () {
        final fallbackName = 'Contact ${recent.participantId}';
        return ContactSummary(
          participantId: recent.participantId,
          displayName: fallbackName,
          autoGeneratedName: fallbackName,
          totalChats: 0,
          totalMessages: 0,
          origin: ParticipantOrigin.working,
          handleCount: 0,
          // No AddressBook data for fallback
          givenName: null,
          familyName: null,
          organization: null,
        );
      },
    );

    results.add(
      RecentContactSummary(
        participantId: contact.participantId,
        displayName: contact.displayName,
        lastAccessedUtc: recent.lastInteractionUtc != null
            ? DateTime.parse(recent.lastInteractionUtc!)
            : DateTime.parse(recent.createdAtUtc),
      ),
    );
  }

  return results;
}
