import 'package:flutter_test/flutter_test.dart';
import 'package:remember_this_text/essentials/source_scoped_import/domain/known_sources.dart';
import 'package:remember_this_text/essentials/source_scoped_import/domain/source_scoped_row_key.dart';
import 'package:remember_this_text/features/contacts/application/read_models/contact_summary.dart';
import 'package:remember_this_text/features/contacts/application/read_models/contact_summary_identity.dart';
import 'package:remember_this_text/features/contacts/domain/participant_origin.dart';

void main() {
  test(
    'canonicalContactIdentityKey converts rowid-keyed contact ids to graph ids',
    () {
      final graphContactId = SourceScopedRowKey.pack(
        sourceId: liveAddressBookSourceId,
        sourceRowId: 17,
      );

      expect(canonicalContactIdentityKey(17), graphContactId);
      expect(canonicalContactIdentityKey(graphContactId), graphContactId);
    },
  );

  test('finds graph contact by rowid-keyed overlay id', () {
    final graphContactId = SourceScopedRowKey.pack(
      sourceId: liveAddressBookSourceId,
      sourceRowId: 17,
    );
    final contacts = [_contact(graphContactId, 'Claire')];

    final contact = findContactSummaryById(contacts, 17);

    expect(contact?.participantId, graphContactId);
  });

  test('does not match unrelated source-scoped contact ids', () {
    final graphContactId = SourceScopedRowKey.pack(
      sourceId: liveAddressBookSourceId,
      sourceRowId: 17,
    );
    final nonAddressBookId = SourceScopedRowKey.pack(
      sourceId: liveChatDbSourceId,
      sourceRowId: 17,
    );
    final contacts = [_contact(graphContactId, 'Claire')];

    final contact = findContactSummaryById(contacts, nonAddressBookId);

    expect(contact, isNull);
  });

  test('preserves app-owned virtual contact ids', () {
    const virtualContactId = 1000000000;

    expect(canonicalContactIdentityKey(virtualContactId), virtualContactId);
    expect(contactIdentityKeyVariants(virtualContactId), {virtualContactId});
  });
}

ContactSummary _contact(int participantId, String name) {
  return ContactSummary(
    participantId: participantId,
    displayName: name,
    autoGeneratedName: name,
    totalChats: 1,
    totalMessages: 1,
    origin: ParticipantOrigin.working,
    handleCount: 1,
  );
}
