import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import 'package:remember_this_text/essentials/db/feature_level_providers.dart';
import 'package:remember_this_text/essentials/db/infrastructure/data_sources/local/conversation_graph/conversation_graph_database.dart';
import 'package:remember_this_text/essentials/db/infrastructure/data_sources/local/overlay/overlay_database.dart';
import 'package:remember_this_text/essentials/source_scoped_import/domain/known_sources.dart';
import 'package:remember_this_text/essentials/source_scoped_import/domain/source_scoped_row_key.dart';
import 'package:remember_this_text/features/contacts/domain/participant_origin.dart';
import 'package:remember_this_text/features/contacts/feature_level_providers.dart';

import '../../../essentials/conversation_graph/conversation_graph_test_database.dart';

void main() {
  group('contactsListRepositoryProvider', () {
    late OverlayDatabase overlayDb;
    late ConversationGraphDatabase graphDb;
    late ProviderContainer container;

    setUp(() async {
      overlayDb = OverlayDatabase(NativeDatabase.memory());
      graphDb = await openConversationGraphTestDatabase();

      container = ProviderContainer(
        overrides: [
          overlayDatabaseProvider.overrideWith((ref) async => overlayDb),
          driftConversationGraphDatabaseProvider.overrideWith(
            (ref) async => graphDb,
          ),
        ],
      );
    });

    tearDown(() async {
      await overlayDb.close();
      await graphDb.close();
      container.dispose();
    });

    test(
      'uses graph contacts with chat participation and display override',
      () async {
        await _insertGraphContact(
          graphDb,
          contactId: 9001,
          displayName: 'Claire Merriman Campbell',
          handleId: 7001,
          chatId: 5001,
          messageId: 8001,
        );
        await graphDb.database.insert('contacts', <String, Object?>{
          'contact_id': 9002,
          'display_name': 'Future Sender',
          'given_name': 'Future',
          'family_name': 'Sender',
        });
        await graphDb.database.insert('contact_to_handle', <String, Object?>{
          'contact_id': 9002,
          'handle_ss_id': 7002,
          'handle_value': '+15550000000',
        });
        await overlayDb.setParticipantDisplayNameOverride(9001, 'Claire');

        final results = await container.read(
          contactsListRepositoryProvider.future,
        );

        expect(results, hasLength(1));
        expect(results.single.participantId, 9001);
        expect(results.single.displayName, 'Claire');
        expect(results.single.autoGeneratedName, 'Claire Merriman Campbell');
        expect(results.single.origin, ParticipantOrigin.overlayOverride);
        expect(results.single.totalChats, 1);
        expect(results.single.totalMessages, 1);
        expect(results.single.handleCount, 1);
      },
    );

    test(
      'applies retained-keyed overlay override to graph contact summaries',
      () async {
        const retainedContactId = 24;
        final graphContactId = SourceScopedRowKey.pack(
          sourceId: liveAddressBookSourceId,
          sourceRowId: retainedContactId,
        );
        await _insertGraphContact(
          graphDb,
          contactId: graphContactId,
          displayName: 'Claire Merriman Campbell',
          handleId: 7001,
          chatId: 5001,
          messageId: 8001,
        );
        await overlayDb.setParticipantDisplayNameOverride(
          retainedContactId,
          'Claire',
        );

        final results = await container.read(
          contactsListRepositoryProvider.future,
        );

        expect(results, hasLength(1));
        expect(results.single.participantId, graphContactId);
        expect(results.single.displayName, 'Claire');
        expect(results.single.autoGeneratedName, 'Claire Merriman Campbell');
        expect(results.single.origin, ParticipantOrigin.overlayOverride);
      },
    );

    test(
      'prefers graph-keyed overlay override over retained contact variant',
      () async {
        const retainedContactId = 24;
        final graphContactId = SourceScopedRowKey.pack(
          sourceId: liveAddressBookSourceId,
          sourceRowId: retainedContactId,
        );
        await _insertGraphContact(
          graphDb,
          contactId: graphContactId,
          displayName: 'Claire Merriman Campbell',
          handleId: 7001,
          chatId: 5001,
          messageId: 8001,
        );
        await overlayDb.setParticipantDisplayNameOverride(
          retainedContactId,
          'Retained Claire',
        );
        await overlayDb.setParticipantDisplayNameOverride(
          graphContactId,
          'Graph Claire',
        );

        final results = await container.read(
          contactsListRepositoryProvider.future,
        );

        expect(results, hasLength(1));
        expect(results.single.participantId, graphContactId);
        expect(results.single.displayName, 'Graph Claire');
        expect(results.single.autoGeneratedName, 'Claire Merriman Campbell');
        expect(results.single.origin, ParticipantOrigin.overlayOverride);
      },
    );

    test('includes virtual participants with graph-derived metrics', () async {
      final graphHandleId = SourceScopedRowKey.pack(
        sourceId: liveChatDbSourceId,
        sourceRowId: 42,
      );
      await _insertGraphConversationForHandle(
        graphDb,
        handleId: graphHandleId,
        chatId: 5001,
        messageId: 8001,
      );

      final virtualParticipant = await overlayDb.createVirtualParticipant(
        displayName: 'Virtual Friend',
      );

      await overlayDb.setHandleVirtualParticipantOverride(
        42,
        virtualParticipant.id,
      );

      final results = await container.read(
        contactsListRepositoryProvider.future,
      );

      expect(results, hasLength(1));
      expect(results.single.participantId, virtualParticipant.id);
      expect(results.single.origin, ParticipantOrigin.overlayVirtual);
      expect(results.single.displayName, 'Virtual Friend');
      expect(results.single.totalChats, 1);
      expect(results.single.totalMessages, 1);
      expect(results.single.handleCount, equals(1));
      expect(results.single.isVirtual, isTrue);
    });

    test('deduplicates retained and graph overlay handle counts', () async {
      final graphHandleId = SourceScopedRowKey.pack(
        sourceId: liveChatDbSourceId,
        sourceRowId: 42,
      );
      await _insertGraphConversationForHandle(
        graphDb,
        handleId: graphHandleId,
        chatId: 5001,
        messageId: 8001,
      );

      final virtualParticipant = await overlayDb.createVirtualParticipant(
        displayName: 'Virtual Friend',
      );

      await overlayDb.setHandleVirtualParticipantOverride(
        42,
        virtualParticipant.id,
      );
      await overlayDb.setHandleVirtualParticipantOverride(
        graphHandleId,
        virtualParticipant.id,
      );

      final results = await container.read(
        contactsListRepositoryProvider.future,
      );

      expect(results, hasLength(1));
      expect(results.single.participantId, virtualParticipant.id);
      expect(results.single.handleCount, equals(1));
    });

    test('omits graph contacts that have not participated in chats', () async {
      await graphDb.database.insert('contacts', <String, Object?>{
        'contact_id': 9003,
        'display_name': 'Unlinked Person',
      });
      await graphDb.database.insert('contact_to_handle', <String, Object?>{
        'contact_id': 9003,
        'handle_ss_id': 7003,
        'handle_value': '+15550000003',
      });

      final results = await container.read(
        contactsListRepositoryProvider.future,
      );

      expect(results, isEmpty);
    });

    test('omits virtual participants without graph chat evidence', () async {
      final virtualParticipant = await overlayDb.createVirtualParticipant(
        displayName: 'Virtual No Chat',
      );
      await overlayDb.setHandleVirtualParticipantOverride(
        43,
        virtualParticipant.id,
      );

      final results = await container.read(
        contactsListRepositoryProvider.future,
      );

      expect(results, isEmpty);
    });
  });
}

Future<void> _insertGraphContact(
  ConversationGraphDatabase graphDb, {
  required int contactId,
  required String displayName,
  required int handleId,
  required int chatId,
  required int messageId,
}) async {
  await graphDb.database.insert('contacts', <String, Object?>{
    'contact_id': contactId,
    'display_name': displayName,
    'given_name': displayName.split(' ').first,
    'family_name': displayName.split(' ').last,
  });
  await graphDb.database.insert('contact_to_handle', <String, Object?>{
    'contact_id': contactId,
    'handle_ss_id': handleId,
    'handle_value': '+17789908506',
  });
  await _insertGraphConversationForHandle(
    graphDb,
    handleId: handleId,
    chatId: chatId,
    messageId: messageId,
  );
}

Future<void> _insertGraphConversationForHandle(
  ConversationGraphDatabase graphDb, {
  required int handleId,
  required int chatId,
  required int messageId,
}) async {
  await graphDb.database.insert('handles', <String, Object?>{
    'ss_id': handleId,
    'id': '+17789908506',
    'service': 'iMessage',
  });
  await graphDb.database.insert('chat_to_handle', <String, Object?>{
    'chat_ss_id': chatId,
    'handle_ss_id': handleId,
  });
  await graphDb.database.insert('chat_to_message', <String, Object?>{
    'chat_ss_id': chatId,
    'message_ss_id': messageId,
  });
  await graphDb.database.insert('messages', <String, Object?>{
    'ss_id': messageId,
    'guid': 'guid-$messageId',
    'is_from_me': 0,
    'date_utc': '2026-05-20T10:00:00.000Z',
  });
}
