import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import 'package:remember_this_text/features/contacts/application/sidebar_cassette_spec/resolver_tools/participants_for_picker_provider.dart';
import 'package:remember_this_text/features/contacts/domain/participant_origin.dart';
import 'package:remember_this_text/features/contacts/infrastructure/repositories/contacts_list_repository.dart';

void main() {
  group('participantsForPickerProvider', () {
    test('maps contact summaries into picker participants', () async {
      final container = _containerWithContacts([
        _contactSummary(
          participantId: 1,
          displayName: 'Existing Person',
          origin: ParticipantOrigin.working,
          handleCount: 1,
        ),
        _contactSummary(
          participantId: 2,
          displayName: 'Virtual Friend',
          origin: ParticipantOrigin.overlayVirtual,
          handleCount: 1,
        ),
      ]);
      addTearDown(container.dispose);

      final results = await container.read(
        participantsForPickerProvider(searchQuery: '').future,
      );

      expect(results, hasLength(2));
      expect(results.first.origin, ParticipantOrigin.working);
      expect(results.first.handleCount, equals(1));
      expect(results.last.origin, ParticipantOrigin.overlayVirtual);
      expect(results.last.displayName, equals('Virtual Friend'));
      expect(results.last.handleCount, equals(1));
      expect(results.last.isVirtual, isTrue);
    });

    test('filters participants by search query', () async {
      final container = _containerWithContacts([
        _contactSummary(
          participantId: 1,
          displayName: 'Alice Wonderland',
          origin: ParticipantOrigin.working,
          handleCount: 1,
        ),
        _contactSummary(
          participantId: 2,
          displayName: 'Overlay Only',
          origin: ParticipantOrigin.overlayVirtual,
          handleCount: 1,
        ),
      ]);
      addTearDown(container.dispose);

      final results = await container.read(
        participantsForPickerProvider(searchQuery: 'overlay').future,
      );

      expect(results, hasLength(1));
      expect(results.first.id, 2);
      expect(results.first.origin, ParticipantOrigin.overlayVirtual);
    });

    test(
      'returns empty when the contact repository returns no contacts',
      () async {
        final container = _containerWithContacts(const []);
        addTearDown(container.dispose);

        final results = await container.read(
          participantsForPickerProvider(searchQuery: '').future,
        );

        expect(results, isEmpty);
      },
    );
  });
}

ProviderContainer _containerWithContacts(List<ContactSummary> contacts) {
  return ProviderContainer(
    overrides: [
      contactsListRepositoryProvider.overrideWith((ref) async => contacts),
    ],
  );
}

ContactSummary _contactSummary({
  required int participantId,
  required String displayName,
  required ParticipantOrigin origin,
  required int handleCount,
}) {
  return ContactSummary(
    participantId: participantId,
    displayName: displayName,
    autoGeneratedName: displayName,
    totalChats: 1,
    totalMessages: 1,
    origin: origin,
    handleCount: handleCount,
  );
}
