import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:macos_ui/macos_ui.dart';

import '../../../feature_level_providers.dart';
import '../../../presentation/dialogs/contact_name_edit_dialog.dart';
import '../../../presentation/widgets/contact_cassette_error.dart';
import '../../../presentation/widgets/contact_highlight_row.dart';
import '../../read_models/contact_summary_identity.dart';
import '../resolver_tools/contact_display_name_override_actions_provider.dart';
import '../resolver_tools/contact_favorite_actions_provider.dart';
import '../resolver_tools/contact_is_favorite_provider.dart';

/// Widget builder for the contact hero summary cassette.
///
/// Displays detailed information about a selected contact including
/// display name (editable), identity anchor, and metadata summary.
///
/// ## Contract (from 00-cross-surface-spec-system.md)
///
/// Widget builders:
/// - Accept fully-decided inputs (not specs)
/// - May use `ref.watch()` for reactive updates
/// - Dispatch semantic actions on user interaction; do not construct panel specs
class ContactHeroSummaryWidget extends ConsumerStatefulWidget {
  const ContactHeroSummaryWidget({super.key, required this.contactId});

  /// The ID of the contact to display.
  final int contactId;

  @override
  ConsumerState<ContactHeroSummaryWidget> createState() =>
      _ContactHeroSummaryWidgetState();
}

class _ContactHeroSummaryWidgetState
    extends ConsumerState<ContactHeroSummaryWidget> {
  ContactSummary? _displayedContact;

  @override
  void didUpdateWidget(covariant ContactHeroSummaryWidget oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (oldWidget.contactId != widget.contactId) {
      _displayedContact = null;
    }
  }

  @override
  Widget build(BuildContext context) {
    ref.listen<AsyncValue<List<ContactSummary>>>(
      contactsListRepositoryProvider,
      (_, next) {
        next.whenData((contacts) {
          final nextSelected = _findContactById(contacts, widget.contactId);
          if (nextSelected == null) {
            return;
          }

          final displayedContact = _displayedContact;
          if (displayedContact == null ||
              _shouldRefreshDisplayedContact(
                current: displayedContact,
                next: nextSelected,
              )) {
            setState(() {
              _displayedContact = nextSelected;
            });
          }
        });
      },
    );

    final contactsAsync = ref.read(contactsListRepositoryProvider);
    final selectedContact = contactsAsync.valueOrNull == null
        ? null
        : _findContactById(contactsAsync.valueOrNull!, widget.contactId);
    final displayedContact = _resolveDisplayedContact(selectedContact);

    if (displayedContact != null) {
      return _buildHeroSummary(
        context: context,
        ref: ref,
        contact: displayedContact,
      );
    }

    return contactsAsync.when(
      data: (_) => const Text('Selected contact not found.'),
      loading: () => const Center(child: ProgressCircle()),
      error: (error, _) => ContactCassetteError(
        onRetry: () {
          ref.invalidate(contactsListRepositoryProvider);
        },
        message: '$error',
      ),
    );
  }

  Widget _buildHeroSummary({
    required BuildContext context,
    required WidgetRef ref,
    required ContactSummary contact,
  }) {
    final isFavoriteAsync = ref.watch(
      contactIsFavoriteProvider(participantId: widget.contactId),
    );
    final isFavorite = isFavoriteAsync.valueOrNull ?? false;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        ContactHeroHeaderHighlight(
          displayName: contact.displayName,
          autoGeneratedName: contact.autoGeneratedName,
          summaryLine: _buildSummaryLine(contact),
          onEdit: () => _handleEdit(context, ref, contact),
          isFavorite: isFavorite,
          onToggleFavorite: (wantsFavorite) =>
              _handleToggleFavorite(ref, contact.participantId, wantsFavorite),
        ),
        const SizedBox(height: 2),
      ],
    );
  }

  ContactSummary? _resolveDisplayedContact(ContactSummary? selectedContact) {
    final displayedContact = _displayedContact;
    if (displayedContact != null &&
        contactSummaryMatchesId(displayedContact, widget.contactId)) {
      return displayedContact;
    }

    return selectedContact;
  }

  ContactSummary? _findContactById(List<ContactSummary> contacts, int id) {
    return findContactSummaryById(contacts, id);
  }

  Future<void> _handleEdit(
    BuildContext context,
    WidgetRef ref,
    ContactSummary contact,
  ) async {
    // Show the edit dialog
    final result = await showContactNameEditDialog(
      context: context,
      ref: ref,
      contact: contact,
    );

    // null = cancelled, do nothing
    if (result == null) {
      return;
    }

    // Empty string = clear override (use auto-generated name)
    // Non-empty = set custom name
    final newDisplayName = result.isEmpty ? null : result;

    await ref
        .read(contactDisplayNameOverrideActionsProvider.notifier)
        .setDisplayNameOverride(
          contactId: contact.participantId,
          displayName: newDisplayName,
        );
  }

  Future<void> _handleToggleFavorite(
    WidgetRef ref,
    int participantId,
    bool wantsFavorite,
  ) async {
    await ref
        .read(contactFavoriteActionsProvider.notifier)
        .setFavorite(contactId: participantId, isFavorite: wantsFavorite);
  }
}

bool _shouldRefreshDisplayedContact({
  required ContactSummary current,
  required ContactSummary next,
}) {
  return current.participantId != next.participantId ||
      current.displayName != next.displayName ||
      current.autoGeneratedName != next.autoGeneratedName ||
      current.origin != next.origin ||
      current.handleCount != next.handleCount ||
      current.givenName != next.givenName ||
      current.familyName != next.familyName ||
      current.organization != next.organization;
}

/// Builds a human-readable summary line for the contact.
String _buildSummaryLine(ContactSummary contact) {
  final chatLabel = contact.totalChats == 1 ? 'chat' : 'chats';
  final messageLabel = contact.totalMessages == 1 ? 'message' : 'messages';
  return '${contact.totalChats} $chatLabel · ${contact.totalMessages} $messageLabel';
}
