import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:macos_ui/macos_ui.dart';

import '../../../../../essentials/db/feature_level_providers.dart';
import '../../../infrastructure/repositories/contacts_list_repository.dart';
import '../../../presentation/dialogs/contact_name_edit_dialog.dart';
import '../../../presentation/widgets/contact_cassette_error.dart';
import '../../../presentation/widgets/contact_highlight_row.dart';
import '../resolver_tools/contact_is_favorite_provider.dart';
import '../resolver_tools/favorite_contacts_provider.dart';
import '../resolver_tools/favorite_contacts_repository_provider.dart';
import '../resolver_tools/unified_picker_sections_provider.dart';

/// Widget builder for the contact hero summary cassette.
///
/// Displays detailed information about a selected contact including
/// display name (editable), identity anchor, and metadata summary.
///
/// ## Contract (from 00-cross-surface-spec-system.md)
///
/// Widget builders:
/// - Accept fully-decided inputs (not specs)
/// - May use `ref.watch()` for reactive updates
/// - Construct specs only on user interaction (output, not interpretation)
class ContactHeroSummaryWidget extends ConsumerWidget {
  const ContactHeroSummaryWidget({super.key, required this.contactId});

  /// The ID of the contact to display.
  final int contactId;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final contactsAsync = ref.watch(contactsListRepositoryProvider);

    return contactsAsync.when(
      data: (contacts) {
        final selectedContact = _findContactById(contacts, contactId);

        if (selectedContact == null) {
          return const Text('Selected contact not found.');
        }

        // Reactively watch favorite status for this contact.
        final isFavoriteAsync = ref.watch(
          contactIsFavoriteProvider(participantId: contactId),
        );
        final isFavorite = isFavoriteAsync.valueOrNull ?? false;
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            ContactHeroHeaderHighlight(
              displayName: selectedContact.displayName,
              autoGeneratedName: selectedContact.autoGeneratedName,
              summaryLine: _buildSummaryLine(selectedContact),
              onEdit: () => _handleEdit(context, ref, selectedContact),
              isFavorite: isFavorite,
              onToggleFavorite: (wantsFavorite) => _handleToggleFavorite(
                ref,
                selectedContact.participantId,
                wantsFavorite,
              ),
            ),
            const SizedBox(height: 2),
          ],
        );
      },
      loading: () => const Center(child: ProgressCircle()),
      error: (error, _) => ContactCassetteError(
        onRetry: () {
          ref.invalidate(contactsListRepositoryProvider);
        },
        message: '$error',
      ),
    );
  }

  ContactSummary? _findContactById(List<ContactSummary> contacts, int id) {
    for (final contact in contacts) {
      if (contact.participantId == id) {
        return contact;
      }
    }
    return null;
  }

  Future<void> _handleEdit(
    BuildContext context,
    WidgetRef ref,
    ContactSummary contact,
  ) async {
    // Show the edit dialog
    final result = await showContactNameEditDialog(
      context: context,
      ref: ref,
      contact: contact,
    );

    // null = cancelled, do nothing
    if (result == null) {
      return;
    }

    // Get the overlay database
    final overlayDb = await ref.read(overlayDatabaseProvider.future);

    // Empty string = clear override (use auto-generated name)
    // Non-empty = set custom name
    final newDisplayName = result.isEmpty ? null : result;

    // Save to overlay database
    await overlayDb.setParticipantDisplayNameOverride(
      contact.participantId,
      newDisplayName,
    );

    // Invalidate contacts list to refresh the UI
    ref.invalidate(contactsListRepositoryProvider);
  }

  /// Add or remove a contact from favorites and invalidate dependent providers.
  Future<void> _handleToggleFavorite(
    WidgetRef ref,
    int participantId,
    bool wantsFavorite,
  ) async {
    final repository = await ref.read(
      favoriteContactsRepositoryProvider.future,
    );

    if (wantsFavorite) {
      await repository.addFavorite(participantId: participantId);
    } else {
      await repository.removeFavorite(participantId);
    }

    // Drive reactivity: invalidate the is-favorite check and the picker
    // sections that depend on the favorites list.
    ref.invalidate(contactIsFavoriteProvider(participantId: participantId));
    ref.invalidate(favoriteContactsProvider);
    ref.invalidate(unifiedPickerSectionsProvider);
  }
}

/// Builds a human-readable summary line for the contact.
String _buildSummaryLine(ContactSummary contact) {
  final chatLabel = contact.totalChats == 1 ? 'chat' : 'chats';
  final messageLabel = contact.totalMessages == 1 ? 'message' : 'messages';
  return '${contact.totalChats} $chatLabel · ${contact.totalMessages} $messageLabel';
}
